#
# Build preview packages for internal feed
#
parameters:
- name: upload
  type: string
  default: False
  values: 
  - False
  - True
- name: config
  type: string
  default: Release
  values: 
  - Debug
  - Release

jobs:
- job: nuget${{parameters.config}}
  displayName: Pack Nugets ${{parameters.config}}
  pool:
    vmImage: 'windows-2022'
  variables:
  - group: codesign
  - name: msbuildversion
    value: '/p:Version=$(NBGV_Version) /p:AssemblyVersion=$(NBGV_SimpleVersion) /p:FileVersion=$(NBGV_AssemblyFileVersion)'
  - name: msbuildsign
    value: '/p:AssemblyOriginatorKeyFile=$(strongnamefile.secureFilePath) /p:SignAssembly=true'
  - name: nugetversion
    value: '$(NBGV_NuGetPackageVersion)'
  - name: signinglist
    value: '.azurepipelines/signlist${{parameters.config}}.txt'
  steps:
  - checkout: self
    fetchDepth: 0  # fetch all commits for versioning
  - task: UseDotNet@2
    displayName: 'Install .NET 10.0'
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
      includePreviewVersions: false  
  - task: DownloadSecureFile@1
    name: strongnamefile
    displayName: 'Download Strong Name Key'
    inputs:
      secureFile: 'CryptoHives.Foundation.Key.snk'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --version 3.0.0 --tool-path . azuresigntool'
    displayName: Install AzureSignTool
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --version 3.0.45 --tool-path . NuGetKeyVaultSignTool'
    displayName: Install NuGetKeyVaultSignTool
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=5.8.x'
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/set-version.ps1
  - task: DotNetCoreCLI@2
    displayName: Restore ${{parameters.config}}
    inputs:
      command: restore
      projects: 'CryptoHives .NET Foundation.sln'
      arguments: '--configuration ${{parameters.config}}'
      restoreArguments: '--disable-parallel'
  - task: DotNetCoreCLI@2
    displayName: Build ${{parameters.config}}
    inputs:
      command: build
      projects: 'CryptoHives .NET Foundation.sln'
      arguments: '--no-incremental --configuration ${{parameters.config}} ${{ variables.msbuildversion }} ${{ variables.msbuildsign }}'
  - task: CmdLine@2
    displayName: 'List of assemblies to sign'
    inputs:
      script: |
        dir /b /s src\CryptoHives.*.dll > .\list.txt
        dir /b /s .azurepipelines\*.* >> .\list.txt
        type .\list.txt
  - task: CmdLine@2
    displayName: 'Sign Assemblies'
    condition: ne( variables['SigningClientSecret'], '')
    inputs:
      script: |
        azuresigntool sign -du "$(SigningURL)" -kvu "$(SigningVaultURL)" -kvt "$(SigningTenantId)" -kvi "$(SigningClientId)" -tr http://timestamp.digicert.com -td sha384 -kvs "$(SigningClientSecret)" -kvc "$(SigningCertName)" -v -ifl ${{ variables.signinglist }}
  - task: DotNetCoreCLI@2
    displayName: Pack Nuget ${{parameters.config}}
    inputs:
      command: pack
      packagesToPack:  'CryptoHives .NET Foundation.sln'
      configuration: ${{parameters.config}}
      configurationToPack: ${{parameters.config}}
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'nugetversion'
      nobuild: true
  - task: CmdLine@2
    displayName: 'List of nuget packages to sign'
    inputs:
      script: |
        dir /b /s $(Build.ArtifactStagingDirectory)\CryptoHives.*.*nupkg > .\nupkglist.txt
        type .\nupkglist.txt
  - task: CmdLine@2
    displayName: Sign Nuget packages
    condition: and(succeeded(), ne( variables['SigningClientSecret'], ''))
    continueOnError: true
    inputs:
      script: |
        NuGetKeyVaultSignTool sign $(Build.ArtifactStagingDirectory)/**/CryptoHives.*.nupkg --file-digest sha256 --timestamp-rfc3161 http://timestamp.digicert.com --timestamp-digest sha256 --azure-key-vault-url "$(SigningVaultURL)" --azure-key-vault-client-id "$(SigningClientId)" --azure-key-vault-tenant-id "$(SigningTenantId)" --azure-key-vault-client-secret "$(SigningClientSecret)" --azure-key-vault-certificate "$(SigningCertName)" 
        NuGetKeyVaultSignTool sign $(Build.ArtifactStagingDirectory)/**/CryptoHives.*.snupkg --file-digest sha256 --timestamp-rfc3161 http://timestamp.digicert.com --timestamp-digest sha256 --azure-key-vault-url "$(SigningVaultURL)" --azure-key-vault-client-id "$(SigningClientId)" --azure-key-vault-tenant-id "$(SigningTenantId)" --azure-key-vault-client-secret "$(SigningClientSecret)" --azure-key-vault-certificate "$(SigningCertName)" 
  - ${{ if eq(parameters.upload, 'True') }}:
    - task: NuGetCommand@2
      displayName: Upload Nuget Preview
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/CryptoHives.*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '$(VSTSFEED)'
        allowPackageConflicts: true
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifacts'
    inputs:
      path: $(Build.ArtifactStagingDirectory)
      artifact: 'cryptohives_${{parameters.config}}_$(NBGV_Version)_$(NBGV_NugetPackageVersion)'
